"""Generate editable crest-body variants from the approved SVG crowns.
Run from repository root. No raster generation; preserves original upper artwork.
"""
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / 'game/presentation/waves'
NS = '{http://www.w3.org/2000/svg}'
ET.register_namespace('', NS[1:-1])

def tag(element):
    return ET.tostring(element, encoding='unicode')

for shape in ['curl', 'double', 'sweep']:
    source = ET.parse(BASE / f'theatre_{shape}.svg').getroot()
    # The three open strokes are the approved top contour, ink/foam/grain.
    crowns = [e for e in source if e.tag == NS+'path' and e.get('stroke-width') in ['22', '15', '2']]
    top = crowns[0].get('d')
    original_group = source.find(NS+'g')
    flow = next(e for e in original_group if e.get('stroke-width') == '4')
    # Keep two long crown-following contours; remove the repeated lower engraving.
    subpaths = flow.get('d').split(' M')
    restrained_flow = subpaths[0] + ' M' + subpaths[1]
    studies = {
        'quiet_cut': {
            'bottom': ' L792 310 C648 321 545 298 397 309 C230 319 117 320 8 315 Z',
            'fill': '#42717e',
            'interior': '<path d="M-10 268 C128 300 220 291 340 270 C493 242 614 295 810 271 L810 420 H-10Z" fill="#294b5b"/>',
            'defs': '',
        },
        'ink_wash': {
            'bottom': ' L792 347 C672 333 561 353 409 337 C259 325 131 357 8 338 Z',
            'fill': 'url(#wash)',
            'interior': '',
            'defs': '<linearGradient id="wash" x1="0" y1="205" x2="0" y2="348" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#42717e"/><stop offset="0.52" stop-color="#335a68"/><stop offset="1" stop-color="#294b5b"/></linearGradient>',
        },
        'long_current': {
            'bottom': ' L792 289 C684 283 612 300 511 306 C357 321 247 308 123 315 C75 317 38 318 8 309 Z',
            'fill': '#42717e',
            'interior': '<path d="M-10 309 C141 298 246 335 390 296 C510 264 624 291 811 267 L811 420 H-10Z" fill="#294b5b"/><path d="M12 291 C139 299 238 279 314 240 C352 220 370 201 380 181 C371 224 343 252 307 267 C213 309 107 305 12 302Z" fill="#90a99f" opacity="0.65"/><path d="M360 300 C449 274 533 282 601 262 C656 246 701 253 787 263 C698 257 670 257 611 277 C526 304 453 286 360 309Z" fill="#6f9696" opacity="0.7"/>',
            'defs': '',
        },
    }
    for name, study in studies.items():
        body = top + study['bottom']
        svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="600" viewBox="0 0 800 400">
<!-- {name}: original curl silhouette and foam edge; redesigned lower body. Generated by scripts/art/build_crest_body_studies.py -->
<defs><clipPath id="new_body"><path d="{body}"/></clipPath>{study['defs']}</defs>
<path d="{body}" fill="{study['fill']}"/>
<g clip-path="url(#new_body)">{study['interior']}<path d="{restrained_flow}" fill="none" stroke="#a4b9ab" stroke-width="3.2" stroke-linecap="round"/></g>
{''.join(tag(e) for e in crowns)}
</svg>
'''
        target = BASE / 'crest_studies' / name / f'theatre_{shape}.svg'
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(svg)
print('Wrote three full families (nine SVGs).')
